services:
  code-server:
    build: .
    container_name: dev-environment
    environment:
      - PASSWORD=${PASSWORD:-devpassword}
      - TZ=${TZ:-UTC}
    expose:
      - "8080"
    volumes:
      - workspace:/home/coder/workspace
      - extensions:/home/coder/.local/share/code-server
    restart: unless-stopped

volumes:
  workspace:
  extensions: