services:
  code-server:
    build: .
    container_name: dev-environment
    environment:
      - PASSWORD=${PASSWORD:-devpassword}
      - TZ=${TZ:-UTC}
      - SERVICE_FQDN_CODESERVER_8080
    healthcheck:
      disable: true
    labels:
      - traefik.enable=true
      - traefik.http.services.codeserver.loadbalancer.server.port=8080
    volumes:
      - workspace:/home/coder/workspace
      - extensions:/home/coder/.local/share/code-server
    restart: unless-stopped

volumes:
  workspace:
  extensions: